### ISSUE TITLE
onUpdate bug

### ISSUE THREAD

**Issue by TimNZ** [DanFessler/react-panelgroup#1]
Great component, thanks!

What argument are you intending to pass to onUpdate callback as this.state.props doesn't exist?
this.state.panels?

```
 componentWillUpdate: function componentWillUpdate() {
    if (this.props.onUpdate) {
      this.props.onUpdate(this.state.props.slice());  
    }
  }
```

**Comment by DanFessler** [comment]
good catch.  the intent was to pass out the panels object, yeah.  Related to this, when you update the props externally it's supposed to update the internal panels state in componentWillReceiveProps, but it's not making a correct props comparison so it wont work.  I'll fix both of these issues.

**Comment by TimNZ** [comment]
Thanks Dan.   

I want to do a mash up of your component and this: http://zippyui.com/docs/react-split-container.
I like it's open/close shortcut feature.

**Comment by DanFessler** [comment]
Pushed a fix.

To do what you want, maintain the panel widths in your container's state and supply it to the PanelGroup as a panelWidths prop.  Stay in sync with the PanelGroup's internal state changes by supplying a hook to props.onUpdate that then updates your container's copy.

With that, you should be able to collapse a panel programmatically or whatever other special thing you want to do.  I tested this scenario locally, but let me know if you get it working too.

**Comment by TimNZ** [comment]
Cheers bro, appreciate your time.

**Comment by TimNZ** [comment]
I'll make some modifications and submit a pull request if I decide to use it for the current project to incorporate more customisability.

Thanks again for it.

**Comment by TimNZ** [comment]
Can you please publish an update to npm.

**Comment by DanFessler** [comment]
Done.  Closing issue
