### ISSUE TITLE
Support React 16

### ISSUE THREAD

**Issue by radekmie** [DanFessler/react-panelgroup#10]
Hello, @DanFessler!

Is there a plan to support React 16? The only _problem_ is the `React.createClass`. If you are OK with it, I'd submit a PR.

**Comment by DanFessler** [comment]
sure, I need to get with the times.  Go for it.

**Comment by ndelangen** [comment]
Need any help with that PR?

**Comment by radekmie** [comment]
Why? It’s already done and waiting for review.

**Comment by krsnaa** [comment]
doesn't appear that it was updated in npm. Installing this package from npm/yarn with react 16 still throws the "react___default.a.createClass is not a function" error.
