### ISSUE TITLE
(NPM) Release Cycle?

### ISSUE THREAD

**Issue by tsneed290** [DanFessler/react-panelgroup#12]
Thank you for your library!

I was wondering what the release cycle is like? How often do you publish to NPM? I'd really like to use this library (and even contribute) for one of my React 16 projects, but the React 16 fixes are not available in NPM yet.

Currently I need to workaround this by cloning the project and pushing to a private NPM repo.

Regards,
Tim

**Comment by stoplion** [comment]
Would like to know this too. In the meantime you can use.
`npm install git://github.com/DanFessler/react-panelgroup.git#master --save`
@tsneed290

**Comment by stoplion** [comment]
Would like to know this too

**Comment by DanFessler** [comment]
there's not really a set release cycle, but I've just pushed an update to NPM now.  Closing this issue :)
