### ISSUE TITLE
Divider: allow custom styling when dragged

### ISSUE THREAD

**Issue by Colmea** [DanFessler/react-panelgroup#13]
Hi,

First, thanks for you lib !
I have an issue and would like to propose a solution.

### Use Case
You often need to custom Divider style when you drag it, like a visual feedback to let user knows he's inside a draggable area. This is currently possible thanks to the `divider` CSS class and a `:hover` on this class.

### Issue
Except that when you're dragging the divider, it happens that your mouse leave -for a second- the Divider area (delay between new panelWidths and render), which cause the lost of the `.divider:hover `.

See this GIF for demo (maybe it's not clear due to low fps, but :hover is often lost when dragging quickly):

![](http://g.recordit.co/lwi9GDWtwe.gif)

### Solution
Add a custom `divider-dragging` class when a Divider is dragging. This way, we can custom style of the Divider when hovered AND when dragged.

I can make a PR if you agree on this one.

**Comment by DanFessler** [comment]
this feature has been merged in.  closing this issue
