### ISSUE TITLE
React 16 support - react___default.a.createClass is not a function

### ISSUE THREAD

**Issue by krsnaa** [DanFessler/react-panelgroup#18]
It doesn't appear that the update was successfully uploaded to npm. Installing this package from npm/yarn with react 16 still throws the "react___default.a.createClass is not a function" error.

Manually compiling the src and copying to node_modules works.

**Comment by DanFessler** [comment]
Sorry about that.  I botched the NPM build.  It should be fine now if you update to latest.  Please confirm if it works for you.

**Comment by krsnaa** [comment]
woooot! 1.0.5 works like a charm! Thanks @DanFessler.
