### ISSUE TITLE
can not resize last child div beyound page.

### ISSUE THREAD

**Issue by kapilpipaliya** [DanFessler/react-panelgroup#19]
is it possible to resize last child div beyound page height when direction="column"?

**Comment by DanFessler** [comment]
Have you tried putting it inside a containing div with a height larger than
the page height?

**Comment by kapilpipaliya** [comment]
no. but i do not have height fixed in containing div. I have a table in a div. when user change page size. it grows its height or gives scrollbar if its not allowed to. so i want to resize panel beyond page size.

**Comment by DanFessler** [comment]
This feature seems out of the scope for the design of the package.  The panels are meant to be resized within a known container rather than change its container. closing.
