### ISSUE TITLE
Panel maxSize

### ISSUE THREAD

**Issue by PGMaster** [DanFessler/react-panelgroup#20]
I am working on an app which requires 3 panes. But the two panes at the end should not expand after a particular limit. It would be good to have **maxSize** to be set for each pane.

**Comment by DanFessler** [comment]
I agree that should be added.  in the meanwhile though you could potentially set a minSize on the left-most panel which would effectively limit how far the other two panels could be expanded.

**Comment by pdfowler** [comment]
@DanFessler I've just submitted a PR with maxWidth functionality. I was really happy to see a multi-panel project that didn't require me to nest in groups of Two. However, maxWidth is a core requirement for us, and I figured it would help the project.

I also broke apart your modules - helps when looking at new code to know where each property/callback/function lives. 😇 

LMK what you think. Cheers!

**Comment by DanFessler** [comment]
@pdfowler left some comments/questions for you on the PR

**Comment by DanFessler** [comment]
resolved in #27
