### ISSUE TITLE
Support for TS typings?

### ISSUE THREAD

**Issue by stemcc** [DanFessler/react-panelgroup#26]
I'm curious if you have any plans for publishing Typescript typings for this, or if for the library itself using Typescript?

**Comment by DanFessler** [comment]
The library isn't written in typescript and I'm not familiar with it too well.  If someone wants to submit typings for it, I'll pull it in.

**Comment by stemcc** [comment]
Thanks, as I start building them on my current project I'll keep you updated - submitting the types to Definitely Typed should really be all that's needed, barring a re-write in TS ;-)

**Comment by gnapse** [comment]
I too would need TypeScript typings. @stemcc were you able to create them? I do not see them in DefinitelyTyped either.
