### ISSUE TITLE
Sizes don't match error

### ISSUE THREAD

**Issue by pallada-92** [DanFessler/react-panelgroup#29]
Got lots of messages like this in console during resize:
`ERROR! SIZES DON'T MATCH!:  532.7000122070312 532.2000122070312`

Perhaps, this is due to non-standard DPI:
`window.devicePixelRatio == 2.5`

I suggest adding threshold of ~2 pixels instead of exact match here: https://github.com/DanFessler/react-panelgroup/blob/master/src/PanelGroup.js#L225

Browser: Chrome Version 70.0.3538.67 (Official Build) (64-bit), Windows 10

**Comment by nicolas-van** [comment]
I proposed a fix here: https://github.com/DanFessler/react-panelgroup/pull/31

**Comment by 18601673727** [comment]
This issue could be really annoying while you were using this package with `@types/react-panelgroup`, which means you cannot switch up to `@tejaskumar/react-panelgroup` for the god sake.

**Comment by DanFessler** [comment]
PR merged.  Closing this
