### ISSUE TITLE
Is that possible to add more style the panel divider?

### ISSUE THREAD

**Issue by JunyuanZheng** [DanFessler/react-panelgroup#3]
Thanks for your project!

I only have 1 question, is that possible to add more style to the panel divider? For instance, animation, etc.

**Comment by radix** [comment]
There is a class applied to the panelgroup and the divider. The PanelGroup has class="panelGroup", panels have class="panelWrapper", and the divider has class="divider".

**Comment by DanFessler** [comment]
this is the correct answer.  Closing issue
