### ISSUE TITLE
Unable to find node on an unmounted component error

### ISSUE THREAD

**Issue by Nemo1181** [DanFessler/react-panelgroup#30]
Hello,

When using version 1.0.7 of the PanelGroup, we get an "Unable to find node on an unmounted component." error from time to time.

![image](https://user-images.githubusercontent.com/34765354/50291328-8b360e00-046e-11e9-8487-67326d87fb55.png)

I could easily reproduce it by creating a test project where the React component using the PanelGroup is replaced by another React component when clicking a button. When clicking this button rapidly, the unmounted errors are shown in the console. It does seem to happen more frequently when my browser/pc is slower or the component using the PanelGroup is more complex.

[react-panelgroup.zip](https://github.com/DanFessler/react-panelgroup/files/2699282/react-panelgroup.zip)

The error seems to be introduced when this.onNextFrame(this.calculateStretchWidth); was put in the Panel.componentDidMount. 

Thanks for the help.

Pieter

**Comment by LekovicMilos** [comment]
Can someone fix this? Still got the issue.

**Comment by DanFessler** [comment]
removed the onNextFrame call in componentDidMount in1.0.8 until I can find a better solution
